// Generated by `pnpm db:types` (scripts/db-types.ts) from the local stack.
// DO NOT EDIT. Numeric columns are typed as decimal STRINGS on purpose — see the script.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      assets: {
        Row: {
          created_at: string
          id: string
          identifier: string
          instrument_kind: string
          metadata: Json
          name: string
          native_currency: string
          pack_id: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          identifier: string
          instrument_kind: string
          metadata?: Json
          name: string
          native_currency: string
          pack_id: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          identifier?: string
          instrument_kind?: string
          metadata?: Json
          name?: string
          native_currency?: string
          pack_id?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      cash_flows: {
        Row: {
          amount: string
          created_at: string
          currency: string
          date: string
          id: string
          note: string | null
          user_id: string
        }
        Insert: {
          amount: string
          created_at?: string
          currency: string
          date: string
          id?: string
          note?: string | null
          user_id: string
        }
        Update: {
          amount?: string
          created_at?: string
          currency?: string
          date?: string
          id?: string
          note?: string | null
          user_id?: string
        }
        Relationships: []
      }
      csv_imports: {
        Row: {
          content: string
          filename: string
          uploaded_at: string
          user_id: string
        }
        Insert: {
          content: string
          filename: string
          uploaded_at?: string
          user_id: string
        }
        Update: {
          content?: string
          filename?: string
          uploaded_at?: string
          user_id?: string
        }
        Relationships: []
      }
      ingest_cursors: {
        Row: {
          last_date: string | null
          last_error: string | null
          last_run_at: string | null
          source_id: string
        }
        Insert: {
          last_date?: string | null
          last_error?: string | null
          last_run_at?: string | null
          source_id: string
        }
        Update: {
          last_date?: string | null
          last_error?: string | null
          last_run_at?: string | null
          source_id?: string
        }
        Relationships: []
      }
      ingest_watermarks: {
        Row: {
          capability: string
          last_date: string | null
          last_run_at: string | null
          ref: string
          source_id: string
          target_from: string
          unavailable_before: string | null
          updated_at: string
        }
        Insert: {
          capability: string
          last_date?: string | null
          last_run_at?: string | null
          ref: string
          source_id: string
          target_from: string
          unavailable_before?: string | null
          updated_at?: string
        }
        Update: {
          capability?: string
          last_date?: string | null
          last_run_at?: string | null
          ref?: string
          source_id?: string
          target_from?: string
          unavailable_before?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      portfolio_snapshots: {
        Row: {
          asset_id: string
          base_currency: string
          carried_forward: boolean
          created_at: string
          date: string
          fx_date: string | null
          fx_rate: string | null
          market_value_base: string
          price_date: string | null
          price_native: string
          quantity: string
          status: string
          user_id: string
        }
        Insert: {
          asset_id: string
          base_currency: string
          carried_forward?: boolean
          created_at?: string
          date: string
          fx_date?: string | null
          fx_rate?: string | null
          market_value_base: string
          price_date?: string | null
          price_native: string
          quantity: string
          status?: string
          user_id: string
        }
        Update: {
          asset_id?: string
          base_currency?: string
          carried_forward?: boolean
          created_at?: string
          date?: string
          fx_date?: string | null
          fx_rate?: string | null
          market_value_base?: string
          price_date?: string | null
          price_native?: string
          quantity?: string
          status?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "snapshots_asset_owner_fk"
            columns: ["asset_id", "user_id"]
            isOneToOne: false
            referencedRelation: "assets"
            referencedColumns: ["id", "user_id"]
          },
        ]
      }
      prices: {
        Row: {
          asset_id: string
          currency: string
          date: string
          price: string
          source_id: string
        }
        Insert: {
          asset_id: string
          currency: string
          date: string
          price: string
          source_id?: string
        }
        Update: {
          asset_id?: string
          currency?: string
          date?: string
          price?: string
          source_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "prices_asset_id_fkey"
            columns: ["asset_id"]
            isOneToOne: false
            referencedRelation: "assets"
            referencedColumns: ["id"]
          },
        ]
      }
      series_points: {
        Row: {
          date: string
          series_id: string
          tenor_days: number
          value: string
        }
        Insert: {
          date: string
          series_id: string
          tenor_days?: number
          value: string
        }
        Update: {
          date?: string
          series_id?: string
          tenor_days?: number
          value?: string
        }
        Relationships: []
      }
      transactions: {
        Row: {
          asset_id: string
          created_at: string
          currency: string
          fees: string
          fx_rate: string | null
          id: string
          note: string | null
          quantity: string
          trade_date: string
          type: Database["public"]["Enums"]["txn_type"]
          unit_price: string
          user_id: string
        }
        Insert: {
          asset_id: string
          created_at?: string
          currency: string
          fees?: string
          fx_rate?: string | null
          id?: string
          note?: string | null
          quantity: string
          trade_date: string
          type: Database["public"]["Enums"]["txn_type"]
          unit_price: string
          user_id: string
        }
        Update: {
          asset_id?: string
          created_at?: string
          currency?: string
          fees?: string
          fx_rate?: string | null
          id?: string
          note?: string | null
          quantity?: string
          trade_date?: string
          type?: Database["public"]["Enums"]["txn_type"]
          unit_price?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "transactions_asset_owner_fk"
            columns: ["asset_id", "user_id"]
            isOneToOne: false
            referencedRelation: "assets"
            referencedColumns: ["id", "user_id"]
          },
        ]
      }
      user_settings: {
        Row: {
          base_currency: string
          created_at: string
          csv_column_map: Json | null
          enabled_packs: string[]
          last_export_at: string | null
          locale: string
          theme: string
          updated_at: string
          user_id: string
        }
        Insert: {
          base_currency?: string
          created_at?: string
          csv_column_map?: Json | null
          enabled_packs?: string[]
          last_export_at?: string | null
          locale?: string
          theme?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          base_currency?: string
          created_at?: string
          csv_column_map?: Json | null
          enabled_packs?: string[]
          last_export_at?: string | null
          locale?: string
          theme?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      asset_latest_prices: {
        Row: {
          asset_id: string | null
          currency: string | null
          date: string | null
          price: string | null
          source_id: string | null
        }
        Relationships: [
          {
            foreignKeyName: "prices_asset_id_fkey"
            columns: ["asset_id"]
            isOneToOne: false
            referencedRelation: "assets"
            referencedColumns: ["id"]
          },
        ]
      }
      snapshot_markers: {
        Row: {
          earliest_trade_date: string | null
          last_snapshot_date: string | null
          last_snapshot_written_at: string | null
          user_id: string | null
        }
        Insert: {
          earliest_trade_date?: never
          last_snapshot_date?: never
          last_snapshot_written_at?: never
          user_id?: string | null
        }
        Update: {
          earliest_trade_date?: never
          last_snapshot_date?: never
          last_snapshot_written_at?: never
          user_id?: string | null
        }
        Relationships: []
      }
      snapshot_totals: {
        Row: {
          base_currency: string | null
          carried_rows: number | null
          date: string | null
          rows: number | null
          stale_rows: number | null
          total_base: string | null
          user_id: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      commit_ingest_chunk: { Args: { payload: Json }; Returns: Json }
      export_backup: { Args: never; Returns: Json }
      restore_backup: { Args: { payload: Json }; Returns: Json }
    }
    Enums: {
      txn_type: "buy" | "sell" | "dividend" | "interest" | "fee"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      txn_type: ["buy", "sell", "dividend", "interest", "fee"],
    },
  },
} as const

