/**
 * `pnpm db:types` — the generated database types, with one correction.
 *
 * `supabase gen types` maps every Postgres `numeric` to a JS `number`. This
 * project never lets a value be a number (CLAUDE.md non-negotiables): every
 * numeric column is written as a decimal string, which Postgres parses
 * exactly, and read back through `::text`. So the generated `number` is
 * simply wrong for this codebase, and leaving it would force `as` casts at
 * every insert and make the typed client lie about what a row carries.
 *
 * This script runs the generator and rewrites `: number` to `: string` for
 * every column that is not a known INTEGER column. A new integer column must
 * be added to the allowlist below; forgetting it fails safe — the column is
 * typed as a string and any arithmetic on it is a compile error, never a
 * silent float. The `Json` union's own `number` member is left alone.
 *
 * Output is deterministic, so CI regenerates the file and fails on a diff.
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

/** Columns that really are integers (counts, tenors), never money or rates. */
const INTEGER_COLUMNS = new Set(["tenor_days", "rows", "stale_rows", "carried_rows"]);

const generated = execFileSync("supabase", ["gen", "types", "typescript", "--local"], { encoding: "utf8" });

const rewritten = generated
  .split("\n")
  .map((line) => {
    // Column lines look like `          quantity: number` / `fx_rate?: number | null`.
    const m = /^(\s+)([a-z_]+)(\??): number(\b.*)$/.exec(line);
    if (!m) return line;
    const [, indent, column, optional, rest] = m;
    if (INTEGER_COLUMNS.has(column)) return line;
    return `${indent}${column}${optional}: string${rest}`;
  })
  .join("\n");

const header = `// Generated by \`pnpm db:types\` (scripts/db-types.ts) from the local stack.
// DO NOT EDIT. Numeric columns are typed as decimal STRINGS on purpose — see the script.
`;
const out = path.resolve(__dirname, "../lib/database.types.ts");
fs.writeFileSync(out, header + rewritten);
console.log(`wrote ${path.relative(process.cwd(), out)}`);
