/**
 * Generates .github/CODEOWNERS from each pack manifest's `maintainers`
 * (PACKS.md §12). Kernel paths require the repository maintainer.
 *
 *   pnpm codeowners          # write
 *   pnpm codeowners --check  # exit 1 if the checked-in file is stale (CI)
 */
import fs from "node:fs";
import path from "node:path";
import { PACKS } from "../packs";

const KERNEL_OWNER = "@mateuscury";
const OUT = path.resolve(__dirname, "../.github/CODEOWNERS");

const lines = [
  "# GENERATED by scripts/generate-codeowners.ts — do not edit by hand.",
  "# Pack owners come from each manifest's `maintainers` (PACKS.md §12).",
  "",
  "# Kernel — maintainer review required",
  `*                          ${KERNEL_OWNER}`,
  `/packs/types.ts            ${KERNEL_OWNER}`,
  `/packs/schema.ts           ${KERNEL_OWNER}`,
  `/packs/index.ts            ${KERNEL_OWNER}`,
  `/packs/LICENSES.md         ${KERNEL_OWNER}`,
  `/packs/conformance/        ${KERNEL_OWNER}`,
  `/lib/                      ${KERNEL_OWNER}`,
  `/supabase/migrations/      ${KERNEL_OWNER}`,
  `/package.json              ${KERNEL_OWNER}`,
  `/pnpm-lock.yaml            ${KERNEL_OWNER}`,
  "",
  "# Packs — owned by their maintainers",
  ...PACKS.map((p) => `/packs/${p.id}/${" ".repeat(Math.max(1, 20 - p.id.length))}${p.maintainers.map((m) => `@${m.replace(/^@/, "")}`).join(" ")}`),
  "",
];
const content = lines.join("\n");

if (process.argv.includes("--check")) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (current !== content) {
    console.error("CODEOWNERS is stale. Run `pnpm codeowners` and commit the result.");
    process.exit(1);
  }
  console.log("CODEOWNERS up to date.");
} else {
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, content);
  console.log(`wrote ${path.relative(process.cwd(), OUT)}`);
}
