/**
 * The typed client (MILESTONES.md §4 decision 49). `Database` is generated by
 * `pnpm db:types` from the local stack and committed; CI regenerates it and
 * fails on a diff, so the types can never drift from the applied migrations.
 * Every factory returns `Db`; every reader and writer takes it.
 */
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database, Json } from "@/lib/database.types";

export type Db = SupabaseClient<Database>;
export type { Database, Json };

/**
 * A plain-data value as PostgREST's `Json`. `Json` is an index-signature
 * type, so a zod-validated interface (a backup, an asset's metadata) is not
 * assignable to it structurally even though it is JSON by construction; this
 * is the one place that gap is bridged, at the RPC or insert boundary.
 */
export function asJson<T>(value: T): Json {
  return value as unknown as Json;
}

/** A table name of the public schema, for helpers that take the table as a parameter. */
export type TableName = keyof Database["public"]["Tables"];
/** A user-scoped table: every one with a `user_id` column, for counts and cascades. */
export type UserTable = {
  [T in TableName]: Database["public"]["Tables"][T]["Row"] extends { user_id: string } ? T : never;
}[TableName];
